language: c
dist: bionic

jobs:
  include:
    - stage: Tests
      name: "Linux"
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:dciabrin/ngdevkit'
            # bionic lacks python3-pygame, so install it from this ppa
            - sourceline: 'ppa:thopiekar/pygame'
          packages:
            - ngdevkit-toolchain
            - python3
            - zip
            - pkg-config
            # ngdevkit-examples deps
            - ngdevkit-gngeo
            - imagemagick
            - libglew-dev
            - libsdl2-dev
      env:
      - PREFIX="/usr"

    - stage: Daily packages
      if: branch = master
      name: Launchpad - deb
      script: skip
      deploy:
        provider: launchpad
        slug: "~dciabrin/ngdevkit/+git/ngdevkit"
        oauth_token:
          secure: "qWe3EuGb7GP0gtlJ6Dyi/U5aI2yfiNg8TzpDA0BonKuE61QcQ4NMDJD58oQNMXL5SY0F+i3LcO/+J20IsxPrBE85Er8P9HUzDT2uaOEAd1EgaL3am+1DyHH4tbF1jfRlbkpYWYR1Ta4r1T/Y9SBZyewRLYJ4jT4MzAjJrFfl/ikvh80d6/xrAESvtM/E1KEUhl/8p7sn3FHvUA0aVhxX1NhPQUzloLGhH986xAnmMqohLwFJqwbK0NNbefsk/qtEG6WMgR07mWIoMR1mIo/IQexZCMqzYwZaNRslvoCfHZaptBsKtC7gUsl2AB8m/O3CDzUuL0Tm2m3gwynyIDm0t9JggcLgDB8ClikaGffjxfKuMLAh7yPCRyDVmE7XJDrFKwc4Wmpoyfvkwg8ojujaX20BusuZxHx60N1sAy37V0+jMHE8UMzEWrm+oYG9qpyP+hfhIsepIWsRHrQLq+MS9kK5lnQGVv5hprCq/YODbTwVvAjhEPRe3Hout4RqlLAeLEjUS7WP5ISXZapSKJMg55Qfo6V+SGqTOLDJWyU8o4xmkqMNpOL1JRoScrvj9vSGQP/NnHmapaNGdzehU73MOBqJz7Gx0fmqLtXhsssL8siwt7cCAr5FOMPbjv2cy6JK6fwoMzRPT04xWHUaZWyiIQCL0OWSQCQ6cOs9AqLUvMU="
        oauth_token_secret:
          secure: "f4PkHZ31F53yQwBiFG4BHtsj50jbtVbCWbezj9Ap8dxUHKM9DgbIbcO8gw/JT/2GM4CPQKky9iFeRHtd5SoMslPCv92lnyLnNT8TGlYszx5MmRARZT+3luNohIywGugcti5BPGAbETblyo0rcnOjbJPCefXSHVdgMsNJRkEtVfZEOBZXn7O6eV7M3lmRjlDzesClX418cOX3Mf1frZZ4W4NScYqDo4eQApZNPWbXq5UIMVzNRbKqx4U3RdQKr2BTH9+n1O5kHhLTuMhWVIZKosYmiW3Ak8Wt3YZrFNHQ+lqPYxvsLkAblugBPT6n5r7Odi/HjgI/4Tr9RdmSSB1/OauBhH7xVFRJ6nTEMFlixZSgf5V0dzD4nPatOIMN6NxQ2xkxYmQFpTj/L9o8MIhObd8cezcU12Yk8C6tLn+6aN90EGM357l3qjL5rQdlWgPPA/DiuVKMmPVOR0509pGH1nKmgZhefC8wFKQzZGKZeA+VSc+/+LNRgEBcAzZGzng9oK73rfspTVHGJsafwkL83e6q/XmZ2S7+1QHbaq3J3mlFCkcgzoyHcoNCiZvVpfrzdNGRiyGXGvUpKpGIRxMCBCNDAGXXXB8kKL1Q00MyQqHj8Qu2hqS5pLEk96Am9ZLA5nH/4JfLSFpO+vh3D01Rw7wHlUEje8vVNvHUcMp/1N0="

script:
  # build
  - autoreconf -iv
  - ./configure --prefix=$PREFIX --enable-external-toolchain --enable-external-emudbg --enable-external-gngeo
  - make && sudo make install
  # tests
  - cd examples
  - export XDG_RUNTIME_DIR=$HOME
  - ./configure && make
